

state_map = {
        'AK': 'Alaska',
        'AL': 'Alabama',
        'AR': 'Arkansas',
        'AS': 'American Samoa',
        'AZ': 'Arizona',
        'CA': 'California',
        'CO': 'Colorado',
        'CT': 'Connecticut',
        'DC': 'District of Columbia',
        'DE': 'Delaware',
        'FL': 'Florida',
        'GA': 'Georgia',
        'GU': 'Guam',
        'HI': 'Hawaii',
        'IA': 'Iowa',
        'ID': 'Idaho',
        'IL': 'Illinois',
        'IN': 'Indiana',
        'KS': 'Kansas',
        'KY': 'Kentucky',
        'LA': 'Louisiana',
        'MA': 'Massachusetts',
        'MD': 'Maryland',
        'ME': 'Maine',
        'MI': 'Michigan',
        'MN': 'Minnesota',
        'MO': 'Missouri',
        'MP': 'Northern Mariana Islands',
        'MS': 'Mississippi',
        'MT': 'Montana',
        'NA': 'National',
        'NC': 'North Carolina',
        'ND': 'North Dakota',
        'NE': 'Nebraska',
        'NH': 'New Hampshire',
        'NJ': 'New Jersey',
        'NM': 'New Mexico',
        'NV': 'Nevada',
        'NY': 'New York',
        'OH': 'Ohio',
        'OK': 'Oklahoma',
        'OR': 'Oregon',
        'PA': 'Pennsylvania',
        'PR': 'Puerto Rico',
        'RI': 'Rhode Island',
        'SC': 'South Carolina',
        'SD': 'South Dakota',
        'TN': 'Tennessee',
        'TX': 'Texas',
        'UT': 'Utah',
        'VA': 'Virginia',
        'VI': 'Virgin Islands',
        'VT': 'Vermont',
        'WA': 'Washington',
        'WI': 'Wisconsin',
        'WV': 'West Virginia',
        'WY': 'Wyoming'
}



stateCodes = {"ALABAMA":"01","ALASKA":"02","ARIZONA":"04","ARKANSAS":"05","CALIFORNIA":"06","COLORADO":"08","CONNECTICUT":"09","DELAWARE":"10","DISTRICT OF COLUMBIA":"11","FLORIDA":"12","GEORGIA":"13","GUAM":"14","HAWAII":"15","IDAHO":"16","ILLINOIS":"17","INDIANA":"18","IOWA":"19","KANSAS":"20","KENTUCKY":"21","LOUISIANA":"22","MAINE":"23","MARYLAND":"24","MASSACHUSETTS":"25","MICHIGAN":"26","MINNESOTA":"27","MISSISSIPPI":"28","MISSOURI":"29","MONTANA":"30","NEBRASKA":"31","NEVADA":"32","NEW HAMPSHIRE":"33","NEW JERSEY":"34","NEW MEXICO":"35","NEW YORK":"36","NORTH CAROLINA":"37","NORTH DAKOTA":"38","OHIO":"39","OKLAHOMA":"40","OREGON":"41","PENNSYLVANIA":"42","PUERTO RICO":"43","RHODE ISLAND":"44","SOUTH CAROLINA":"45","SOUTH DAKOTA":"46","TENNESSEE":"47","TEXAS":"48","UTAH":"49","VERMONT":"50","VIRGINIA":"51","WASHINGTON":"53","WEST VIRGINIA":"54","WISCONSIN":"55","WYOMING":"56"}



company_mapping={
        "COGNIZANT TECHNOLOGY SOLUTIONS US CORPORATION":"COGNIZANT",
        "MICROSOFT CORPORATION":"MICROSOFT",
        "INTEL CORPORATION":"INTEL",
        "GOOGLE INC.":"GOOGLE",
        "AMAZON CORPORATE LLC":"AMAZON",
        "INFOSYS LTD.":"INFOSYS",
        'CISCO SYSTEMS, INC.':'CISCO',
        'ORACLE AMERICA, INC.':'ORACLE',
        'APPLE INC.':"APPLE",
        'QUALCOMM TECHNOLOGIES INC.':"QUALCOMM",
        'DELOITTE CONSULTING LLP':"DELOITTE",
        'FACEBOOK, INC.':"FACEBOOK",
        'HCL AMERICA INC.':"HCL",
        'YAHOO! INC.':"YAHOO",
        'ERNST & YOUNG U.S. LLP':"ERNST & YOUNG",
        'WIPRO LIMITED':"WIPRO",
        'HOUSE OF RAEFORD FARMS, INC.':"HOUSE OF RAEFORD FARMS",
        'JP MORGAN CHASE & CO':"JP MORGAN",
        'IBM CORPORATION':"IBM",
        'IGATE TECHNOLOGIES, INC.':"IGATE"

}